version: 1.26.6.{build}
clone_folder: c:\projects\Npackd
environment:
  matrix:
  - bits: 32
    prg: npackdcl
  - bits: 64
    prg: npackd
  - bits: 64
    prg: npackdcl
  - bits: 32
    prg: npackd
  - bits: 32
    prg: clu
  covtoken:
    secure: yPwsn7ojqxg5m7pxyjIf3LV1GwoHd4m3q5iQrKCDzZ4=
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
- cmd.exe /C AppVeyorInstall.bat
build_script:
- cmd.exe /C AppVeyorBuild.bat
test_script:
- cmd.exe /C AppVeyorTest.bat
deploy:
  description: 'Automated release'
  provider: GitHub
  auth_token:
    secure: TZRXNYgUHwdfwkAfUimkaegIlCs5+UrAKl484ZCxAgvT5TmqA8TKd9nadxXHXDA0
  draft: true
  on:
    appveyor_repo_tag: true
